# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set pom file path
      run: echo "pom_file_path=$(pwd)/pom.xml" >> $GITHUB_ENV

    - name: Build
      run: mvn clean package -f ${{ env.pom_file_path }}

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        maven-version: '3.2.0'  # Thay phiên bản Maven tương ứng
        cache: maven

    - name: Xem chi tiết lỗi pom.xml
      run: mvn clean package -e
    - name: Bật debug logging 
      run: mvn clean package -X


    - name: Validate pom.xml
      run: mvn validate -N

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6


